[build]
  environment = { 
    RUBY_VERSION = "3.2.2", 
    NODE_VERSION = "22" 
  }

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  checkExternal = false

[[plugins]]
package = "netlify-plugin-a11y"
  [plugins.inputs]
   resultMode = "warn"

[[plugins]]
package = "@algolia/netlify-plugin-crawler"

  [plugins.inputs]
  branches = ['main']
  mainBranch = "main"
  disabled = false
  pathPrefix = "/public"
  customDomain = "ble.lternet.edu"
  renderJavaScript = false
  template = "hierarchical"