[build]
  environment = { RUBY_VERSION = "2.6.2" }

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  checkExternal = false

[[plugins]]
package = "netlify-plugin-a11y"
  [plugins.inputs]
   resultMode = "warn"

[[plugins]]
package = "@algolia/netlify-plugin-crawler"

  [plugins.inputs]
  branches = ['master']
  mainBranch = "master"
  disabled = false
  pathPrefix = "/public"
  customDomain = "ble.lternet.edu"
  renderJavaScript = false
  template = "hierarchical"